### ISSUE TITLE
Seamless Homekit migration

### ISSUE THREAD

**Issue by Jafalex** [oznu/homebridge-syno-spk#100]
Hi,
Sorry I couldn't find the answer, but will migrating my current Homebridge instance (via backup upload) to this build mean I will need to start fresh in the iOS Home app? Or will thing pick up as if nothing happened? 
Sorry for the basic question, thanks!

**Comment by Lling** [comment]
This spk will create a new folder on your nas. When you copy/paste your old files in the right folder, it will run flawless. Maybe you will have to reinstall the plugins over the uix. But you dont have to start from the beginning.
