### ISSUE TITLE
Error on DSM 7

### ISSUE THREAD

**Issue by astradti** [oznu/homebridge-syno-spk#101]
it seems i can't get the synology plug-in anymore.
any idea? installed as package, not in docker

![image](https://user-images.githubusercontent.com/108151652/192740021-52da66af-a22c-4d6f-9ff4-c7c1b9bb47ea.png)

**Comment by mikediliberto** [comment]
Same issue here on DSM 7

**Comment by astradti** [comment]
find a partial solution already. Install Git on Synology, then it will install. However the temerature on the plugin doesn't work
