### ISSUE TITLE
Not able to Ping devices through Homebridge

### ISSUE THREAD

**Issue by spera23** [oznu/homebridge-syno-spk#103]
Have tried multiple plugins (all verified) to ping devices to get their on state and I am constantly receive an off state.
Tried pinging directly through terminal on mac and receives state fine.  However when pinging through homebridge installed on Synology drive without docker.....no result.

Any ideas?

**Comment by smathur11** [comment]
I wasn't able to get the People Pro plugin working (https://github.com/mfkrause/homebridge-people-pro#readme) and it uses ping to determine state. I realized that Homebridge didn't have permissions to use the ping binary.  Instead of just opening permissions broadly, this approach worked great for me: http://unixetc.co.uk/2016/05/30/linux-capabilities-and-ping/

**Comment by spera23** [comment]
I think my problem is more related to running homebridge on Synology......cant figure out though

**Comment by spera23** [comment]
> I wasn't able to get the People Pro plugin working (https://github.com/mfkrause/homebridge-people-pro#readme) and it uses ping to determine state. I realized that Homebridge didn't have permissions to use the ping binary. Instead of just opening permissions broadly, this approach worked great for me: http://unixetc.co.uk/2016/05/30/linux-capabilities-and-ping/

@smathur11  Can you confirm how you got this approach working please?

**Comment by smathur11** [comment]
I SSH'd into my Synology and ran this command "$ sudo setcap cap_net_raw+p /bin/ping" as noted in that blog post.

**Comment by spera23** [comment]
> I SSH'd into my Synology and ran this command "$ sudo setcap cap_net_raw+p /bin/ping" as noted in that blog post.

And after you ran this command then your People Pro plugin was working correctly through homebridge?
Thanks!
