### ISSUE TITLE
Support for DS216play

### ISSUE THREAD

**Issue by therealScarabeus** [oznu/homebridge-syno-spk#106]
While this very cool package is available for DS216, DS216j - it is not provided for my DS216play. I would assume they are quite similar (?). Any chance to make this homebridge package available for the play as well? 
Maybe there is only the need to add this Synology device to the list... 
I use it on my DS415+ and it is highly appreciated!

[Edit]
The CPU is a **STM Monaco STiH412**, and so the needed arch would be "Monaco".

Best regards.

**Comment by niekvleeuwen** [comment]
Hi, I am also using an DS216play and would love to use Homebrige on this device! If there is any way I could help make this happen, please let me know.
