### ISSUE TITLE
Synology DS3018xs

### ISSUE THREAD

**Issue by aldobalducci** [oznu/homebridge-syno-spk#11]
hi, I cant seem to install this on my DS3018xs, it says the platform is not supported.
please help. thanks!

**Comment by oznu** [comment]
I'm not sure how to troubleshoot this one as I can't replicate this on my Synology unit or with various DSM units emulated in a VM. If someone with a DS3018xs can figure out the problem with the package please comment here.

**Comment by aldobalducci** [comment]
Is there anything I can do to help?

On 29 May 2018, at 8:37 pm, oznu <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure how to troubleshoot this one as I can't replicate this on my Synology unit or with various DSM units emulated in a VM. If someone with a DS3018xs can figure out the problem with the package please comment here.

**Comment by oznu** [comment]
Hi @aldobalducci,

Can you post as much details as you can about your setup?

* DSM Version
* Installed Docker App Version
* etc.
