### ISSUE TITLE
Host name conflict?

### ISSUE THREAD

**Issue by JDogg016** [oznu/homebridge-syno-spk#12]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/20018778/41010244-295140a2-68eb-11e8-9638-9dcc1909c620.png">

So occasionally, I have an issue where I cannot connect to Homebridge, but everything seems to work meaning I can see cameras and other devices.

I went into the synology docker logs today and I saw the above.  Have you seen this before?

**Comment by oznu** [comment]
The SPK has an option to use "Safe Mode" or the "No avahi" image. Using this will fix the problem.

You can upload the spk again the wizard will ask you what image you want to use, then reconfigure your existing setup.

**Comment by JDogg016** [comment]
So Back in May I had issues with ffmpeg.  You recommended the following:

> For Foscam you'll need to use the debian tag for various reasons.
> 
> The latest update to the offical Homebridge package actually removed the Avahi dependency; so you should be able to use the debian variant of this image now without it crashing due to "hostname conflicts" like it may have done in the past when running on Synology DSM.
> 
> When running on Synology DSM I would recommend installing ffmpeg using the startup.sh script found in the same directory as your config.json, add something like this to the bottom:
> 
> # debian variant only
> 
> apt-get update
> apt-get install -y ffmpeg


I have installed the debian variant.

Do you still recommend the same course of action?

**Comment by oznu** [comment]
You'll need to keep the debian image.

Add this to the bottom of your `startup.sh` script to prevent avahi from starting, then restart the entire container (not just homebridge).

```
rm -rf /etc/services.d/avahi /etc/services.d/dbus
```

This is effectively the same as running the `no-avahi` image.
