### ISSUE TITLE
Can't connect to iOS Home

### ISSUE THREAD

**Issue by chriscrowe** [oznu/homebridge-syno-spk#13]
I've tried the tips listed here: https://github.com/oznu/homebridge-syno-spk/issues/5

At this point I've changed nearly every setting away from default and still I can't get it to connect. For a little while I was actually able to discover it in the Home app but connecting would spin and spin before failing. Then I turned off the container and it was still showing in Home via bonjour, which seemed wrong... So I restarted my phone and it was gone-- but then spun the container back up and it never re-appeared... Now, still connecting with QR and pin is not working. Any thoughts?

**Comment by elmocito** [comment]
Same problem here :-(

**Comment by burnedikt** [comment]
I've ran into the same problem today and after a lot of time wasted, I realized that I did not open up all required ports in my Synology's firewall to allow traffic going through. Both the port for the Configuration-UI and the actual Homebridge must be open in Synology's Firewall. The Apple Home app was able to find the Homebridge without opening these ports previously but connecting to the Homebridge would always fail (spinning and spinning before failing). 

In my case, I had to open both TCP ports **51826 (HomeKit API) and 8581 (Web UI)** in [Synology's Firewall](https://www.synology.com/en-global/knowledgebase/SRM/help/SRM/RouterApp/security_firewall).

**Comment by weiran** [comment]
The problem for me was because I had migrated from a difference instance of homebridge, but copied over the config and it was using the same username as before. I changed the username to any other MAC address, and was then able to add it to my Home app.

**Comment by ChrisChiera** [comment]
Just got a new Synology NAS setup without a problem. Setup this Homebridge Syno SPK without a problem. But when I scan in the code (or enter it manually into Homebridge as an accessory) it says it can't find it. I did have Firewall enabled and saw this thread so for the moment turned firewall off completely and restarted the Synology but same issue? Am running iOS 13, but is there any other issue it could be?

**Comment by joehom0416** [comment]
encounter the same issue with the SPK 2.0, any troubleshoting hint?
