### ISSUE TITLE
Node.js Update

### ISSUE THREAD

**Issue by HonkiDonki** [oznu/homebridge-syno-spk#133]
### Raspberry Pi Model

Other (specify in description)

### Describe The Bug

Hello,

I installed Homebridge on Synology. It works so far.
But how can I update Node.js?
I have version 18.15.0 and would like to update to the latest version.
Unfortunately, I get an error that the installation path is not the correct one. (Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v18/usr/local)
So the normal installation/update doesn't work.

What can I do?

**Comment by NorthernMan54** [comment]
With synology we are leveraging the Synology supplied NodeJS version, and need synology to provide an updated NodeJS version.  So we need to wait for them to provide an update

**Comment by TechDadUK** [comment]
Has there been a progress on this? I have a number of plugins that require a newer node version. Is there an updated node.js version for Synology installations.

**Comment by Perilax-De** [comment]
Node.js 20.9.0-1003 is available on DSM7.

But i get this issue:
`homebridge@DS220plus:/volume1/homebridge $ hb-service update-node 20.9.0
ℹ Installing Node.js v20.9.0 over v18.18.2...
✖ Cannot update Node.js on your system. Non-standard installation path detected: /volume1/@appstore/Node.js_v18/usr/local`

How can I change the path to v20 ?

**Comment by gerstemann** [comment]
In the meanwhile, Synology published a node 20 package. how can I point homebridge to that version of node? How to change the used node path from 18 to the 20 one?

**Comment by NorthernMan54** [comment]
@gerstemann - Node JS is picked here - https://github.com/homebridge/homebridge-syno-spk/blob/latest/app/source.sh

If you could confirm the path for NodeJS 20, we can update the if statement to check for NodeJS 20 as well

https://github.com/homebridge/homebridge-syno-spk/blob/6d29ae1841d0cad0e56225c54e0a5f1f4daf552f/app/source.sh#L7

**Comment by gerstemann** [comment]
Just put a 20 instead of the 18. Thats it.
Do I then have to reinstall the package or is it checking for the new node.js while it updates.

<img width="563" alt="image" src="https://github.com/homebridge/homebridge-syno-spk/assets/50425552/44fadf95-6ebb-4908-940f-cbb27428fb6e">

**Comment by NorthernMan54** [comment]
It checks the version when starting homebridge, so just restart should do it.

**Comment by NorthernMan54** [comment]
Release `3.1.0` has been published with NodeJS 20 support
