### ISSUE TITLE
Can't access Homebridge web interface after upgrading on DS720+

### ISSUE THREAD

**Issue by dficken** [oznu/homebridge-syno-spk#142]
### Raspberry Pi Model

Raspberry Pi 1 B

### Describe The Bug

1. upgraded to 3.0.21 using DSM package manager
2. upgrade reports complete
3. click on Homebridge link 
4. browser failed to open page because URL does not exist.  also seeing greater than normal CPU consumption 90% when normally less than 20%

**Comment by NorthernMan54** [comment]
Duplicate of #141

**Comment by dficken** [comment]
Heard anything?Sent from my iPhoneOn Dec 31, 2023, at 11:16 AM, Northern Man ***@***.***> wrote:﻿
Closed #142 as completed.
