### ISSUE TITLE
Synology has released Nodejs_v20, which can be upgraded.

### ISSUE THREAD

**Issue by primovist** [oznu/homebridge-syno-spk#144]
### Feature Description

![IMG_2358](https://github.com/homebridge/homebridge-syno-spk/assets/2242315/55b805dd-b053-4931-96fc-ec8f51912e13)
![IMG_2359](https://github.com/homebridge/homebridge-syno-spk/assets/2242315/21432827-b74d-4309-bda0-b3da986e81be)

**Comment by primovist** [comment]
#120

**Comment by NorthernMan54** [comment]
I will release an update tomorrow supporting the new version.

if your anxious check the bottom of this issue https://github.com/homebridge/homebridge-syno-spk/issues/133#issuecomment-1874686912

**Comment by NorthernMan54** [comment]
Release `3.1.0` has been published with NodeJS 20 support
