### ISSUE TITLE
Node js.20 needed?

### ISSUE THREAD

**Issue by dbrewood** [oznu/homebridge-syno-spk#146]
### Raspberry Pi Model

Synology NAS DS918+

### Current Situation

Can't update from version 3.0.20 to 3.1.0 as it says Node.js v20 is needed, whereas only version v18 is available from Synology. Any ideas?

**Comment by NorthernMan54** [comment]
https://www.synology.com/en-ca/releaseNote/Node.js_v20?model=DS223

**Comment by dbrewood** [comment]
It turned out I needed to update DSM to the latest version and it was then available for install via the Package Center.

All sorted now :)

**Comment by NorthernMan54** [comment]
Can you share your DSM version so I can update this as well ?

https://github.com/homebridge/homebridge-syno-spk/blob/a0b618f5e5cd214426a5647083598cc69d4dd8f9/INFO.sh#L8

**Comment by dbrewood** [comment]
I updated as follows.....
![Screenshot 2024-01-05 at 12 09 40](https://github.com/homebridge/homebridge-syno-spk/assets/93347139/af034fa4-917f-43ab-b67e-e49bb6947f3b)
Is that all you need? 7.2.1 was the minimum needed IIRC

**Comment by NorthernMan54** [comment]
Tks, will give that a try with the next update

**Comment by NorthernMan54** [comment]
Looking at the release notes, am thinking will update it to - `7.2-64570`

**Comment by dbrewood** [comment]
That may well be viable.

**Comment by hayeskl** [comment]
Node.js 20 is only available to diskstations running version 7.2.  Unfortunately some models cannot upgrade past 7.1 and now cannot update Homebridge to the latest version.

**Comment by dbrewood** [comment]
That is not good news at all. No wortk around I guess?

**Comment by hayeskl** [comment]
If the package is going to require 7.2 and Node.js 20 can it be updated so that the version is marked as not compatible with 7.1.  As it stands now, I keep getting emails saying the package is out of date.

**Comment by NorthernMan54** [comment]
Homebridge is sending emails?

**Comment by hayeskl** [comment]
Synology is sending an email because the package is out of date.

**Comment by NorthernMan54** [comment]
Any idea if synology has a flag we can set in the package to indicate your level is not supported and not send the email ?

Maybe update the `os_min_ver="7.0-40761"` ?

https://github.com/homebridge/homebridge-syno-spk/blob/latest/INFO.sh
