### ISSUE TITLE
Pressing "Install" in package manager downloads the package but doesn't install

### ISSUE THREAD

**Issue by cchewanik** [oznu/homebridge-syno-spk#149]
### Raspberry Pi Model

Other (specify in description)

### Describe The Bug

Running DSM 7.2-64570 Update 1 on DS218+. I press the Install button, it downloads but doesn't install. Any help would be greatly appreciated thank you.

**Comment by NorthernMan54** [comment]
Logs from your DSM would be helpful here.

**Comment by cchewanik** [comment]
Nothing came up in the logs app. Where should I be checking?

**Comment by NorthernMan54** [comment]
Due to #143, I don’t know how to access the logs.  Check other issues here, someone may have shared how

and if you figure how, could you add it to the wiki?

**Comment by cyclonecovey** [comment]
When I press install I see, very briefly, says "loading" and then does nothing.  It won't even download. I don't believe it's a firewall issue. Restart of NAS doesn't change anything.

https://github.com/homebridge/homebridge-syno-spk/assets/8071241/fa009d6b-ae14-45f6-9cb9-33f9d398352e

**Comment by cyclonecovey** [comment]
My issue was web station was using the same port. Deleting the port conflict fixed it.
