### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by jhenson67** [oznu/homebridge-syno-spk#150]
### Describe The Bug

The new update 3.1.1 just installed today 1/9/24.  Nothing shows, blank page.

### Homebridge UI Version

3.1.1

### Homebridge Version

3.1.1

### Node.js Version

v20

### Operating System

Synology DSM

### Environment Info

None

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Logs from your DSM would be useful to see what is happening.
