### ISSUE TITLE
Homebridge on Synology DSM - Fail to update Hombebridge due to Node.JS_v20 requirement which is not available in Synology

### ISSUE THREAD

**Issue by Welasco** [oznu/homebridge-syno-spk#152]
### Analysis

Fail to update Hombebridge due to Node.JS_v20 requirement which is not available in Synology
I'm currently using the version 3.0.20, the system detected a new version available 3.1.1 but it's failing to update because it requires Node.JS_v20.

Print for reference:
![image](https://github.com/homebridge/homebridge/assets/26201510/5f86fb81-4e0d-4a4d-948a-ec780f107c89)

### Expected Behavior

Synology DSM doesn't have a Node.JS_v20 to be installed in their marketplace. The latest version available is Node.js_v18.

Print for reference:
![image](https://github.com/homebridge/homebridge/assets/26201510/7aac952b-8e85-4715-95dc-c89f4bba2c98)

### Steps To Reproduce

Install Homebridge v3.0.20 with Node.JS_v18 and try to upgrade to the latest version v3.1.1.

### Logs

```markdown
Here is the print for reference:
```
![image](https://github.com/homebridge/homebridge/assets/26201510/79cf2d10-3abb-44f2-a673-267b8635a47a)

### Configuration

```json
Not applicable for this issue.
```

### Environment

- OS: Synology DSM, DSM 7.1.1-42962 Update 6, DS918+ 
- Software: DSM 7.1.1-42962 Update 6
- Node: Node.JS_v18
- npm: N/A

### Process Supervisor

other (Explain in `Additional Context`)

### Additional Context

This is a Synology DSM Storage I'm not sure which option the Homebridge package are using for supervisor.

**Comment by NorthernMan54** [comment]
If you look thru the other issues here, people have shared how to locate nodejs 20.

**Comment by kyods** [comment]
Nodejs 20 is not available for my DSM218+ either, which means I'm stuck with DSM 7.1, and unless I'm missing something, I can't really see anybody sharing how to install it in an unsupported DSM version.

**Comment by gabors** [comment]
Is there any update on this issue? 
I also cannot install NodeJS 20 on Synology 1513+ as it cannot be updated to DSM 7.2.
Is there any workaround? 
Do we really need NodeJS 20?

**Comment by Welasco** [comment]
So after reviewing the post here from @gabors I realize I was running 7.1 which doesn't include Node_JS20.
Reading the latest readme files from Synology they mention that DS918+ won't receive an automatically upgrade for 7.2 which offers NodeJS 20.
So I had to manually upgrade it and install NodeJS 20.
Reference:
https://www.synology.com/en-global/releaseNote/DSM

That fix the issue.

**Comment by kyods** [comment]
> So after reviewing the post here from @gabors I realize I was running 7.1 which doesn't include Node_JS20. Reading the latest readme files from Synology they mention that DS918+ won't receive an automatically upgrade for 7.2 which offers NodeJS 20. So I had to manually upgrade it and install NodeJS 20. Reference: https://www.synology.com/en-global/releaseNote/DSM
> 
> That fix the issue.

Thank you! That did the trick for me.

**Comment by gabors** [comment]
Thanks guys but from what I understand DSM 7.2 is not available for my DS1513+, not automatically not manually.
So I can't install NodeJS 20.
Again, is v20 really necessary?

**Comment by stevenharman** [comment]
@gabors Same goes for my DS1515+.

**Comment by stephen-kim** [comment]
There's a DS715 on supported models list in Release page, which is not true. DS715 cannot be updated to DSM7.2 (not even manually).
And I'm running Homebridge in Docker on another linux machine, that Homebridge's Node.js is still v18 and working fine.

So I think it's necessary that synology.homebridge.io repo provides 2 separated packages for old Synology models which is running on Node.js v18.
