### ISSUE TITLE
Not package for package manager - https://synology.homebridge.io/ returns an empty array for the package object.

### ISSUE THREAD

**Issue by cp-bwg** [oznu/homebridge-syno-spk#154]
### Raspberry Pi Model

Other (specify in description)

### Describe The Bug

![empty](https://github.com/homebridge/homebridge-syno-spk/assets/56896857/5f1b38ec-ebaa-4f83-a730-88c5eb538c10)
https://synology.homebridge.io/ returns an empty array for the package object.

This is the URL told in the readme to use when adding a package source to Synology for native package manager installation.

Thus, after adding the source, no package is available when searching Homebridge in the Synology package manager.

**Comment by RickNunn** [comment]
+1

**Comment by paul-eeoc** [comment]
Can we have the packages back?
<img width="708" alt="Screenshot 2024-03-16 at 9 30 04 AM" src="https://github.com/homebridge/homebridge-syno-spk/assets/16565163/d9615136-5fec-4dfb-bd1f-4f4710698c7d">

**Comment by NorthernMan54** [comment]
As a workaround while we investigate this, you could do a manual install of the appropriate SPK file.  We store the SPK files here - https://github.com/homebridge/homebridge-syno-spk/releases

Download the appropriate one, then Go to DSM > Package Center > Manual Install then select your .spk file to do installation.
