### ISSUE TITLE
Explicitly point out unsupported Environments

### ISSUE THREAD

**Issue by Verocoder** [oznu/homebridge-syno-spk#155]
### Proposed Change

To start I'm happy to make the change and I'll put a PR up in a bit, but wanted an issue to discuss it.

I've spent a few days trying to work out which environment my NAS is running as its not one of the listed ones and eventually [tracked ](https://www.synology.com/en-uk/releaseNote/SynologyApplicationService?model=DS423)Comcerto2k based devices dropping node support. I'm proposing adding an unsupported models block under the suppported models one. It would have made my life easier and I think the list is going to grow as more machines fall off the back of node 20 support (another [issue](https://github.com/homebridge/homebridge-syno-spk/issues/152) is relevant with one of the models not supporting newest releases)

### Wiki Page Link

https://github.com/homebridge/homebridge-syno-spk?tab=readme-ov-file#supported-models

**Comment by NorthernMan54** [comment]
Tks very much

Does this interest you ? #143

**Comment by Verocoder** [comment]
I'd read that one and I might have asked more about it but my machine doesn't actually support homebridge so I'm probably not the right guy as I can't test builds at all
