### ISSUE TITLE
Cannot access Homebridge UI after update to 3.1.1

### ISSUE THREAD

**Issue by DukeofArmchair** [oznu/homebridge-syno-spk#163]
### Describe The Bug

I recently updated to Synology package Homebridge 3.1.1 with JS Node V20 and can no longer access my home bridge instance at all. I have uninstalled rebooted, reinstalled and simply cannot login to the Homebridge UI.

### Homebridge UI Version

Not Sure, I cannot access

### Homebridge Version

3.1.1

### Node.js Version

V20

### Operating System

Synology DSM

### Environment Info

None

### Raspberry Pi Model

None

**Comment by NorthernMan54** [comment]
Any log files ?

**Comment by DukeofArmchair** [comment]
Man, I am really sorry I forgot to update the this, I realized I needed to open the port in the FW, I am up and running again. Sorry for the false alarm.

**Comment by NorthernMan54** [comment]
Not a problem sir, glad you resolved it easily
