### ISSUE TITLE
https://synology.homebridge.io is empty

### ISSUE THREAD

**Issue by vanyalaptii** [oznu/homebridge-syno-spk#164]
### Raspberry Pi Model

Other (specify in description)

### Describe The Bug

I following an instruction for installation HomeBridge for DSM 7, and after "Step 1: Add the Homebridge Synology Package Source" is nothing happened and Homebridge is not showing in my package manager.
If I go to https://synology.homebridge.io it shows only {"packages":[]}
Or HomeBridge available only for docker?

**Comment by NorthernMan54** [comment]
The website, https://synology.homebridge.io/ looks are your user-agent string and it should return the appropriate package for your device.  If you use a browser to access the site, you just get the empty package.

**Comment by vanyalaptii** [comment]
Ok, I understand it. But I added url in package manager settings and it's accept it. And when try to find Homebridge package in DS7 package manager or in search its not showing up.
