### ISSUE TITLE
Homebridge UI

### ISSUE THREAD

**Issue by ChalesGiron** [oznu/homebridge-syno-spk#22]
**Brilliant work**! As I encountered the same issues with ip issues after upgrade, this is perfect! Unfortunately the Homebridge UI doesnt let me sign in. It always reports "Invalid Username and Password". Maybe it is an issue with my previous installation? Thanks in advance! C.

**Comment by ceraz68** [comment]
I just noticed this also after updating packages. The default password doesn't work. Re-installing the UI made no difference.

Did you solve the problem?

**Comment by ceraz68** [comment]
I solved my problem. I noticed that the container had lost the environment entry for DSM_HOSTNAME which didn't make a difference. Then reading other posts, I deleted auth.json in the homebridge folder which is recreated when relaunching the container. worked immediately.

Don't know why it lost its password as it was not changed.
