### ISSUE TITLE
Using secondary LAN interface

### ISSUE THREAD

**Issue by thomasrawley** [oznu/homebridge-syno-spk#23]
Is there a way to tell Homebridge (or Docker) to use my secondary LAN interface? I have 2 ethernet connections for my synology, which add it to two different VLANs. I would prefer Homebridge use the non synology default LAN.

**Comment by oznu** [comment]
https://github.com/nfarina/homebridge/issues/2098

**Comment by thomasrawley** [comment]
Impressive response time! I will give a try (probably not tonight) and report back. And thanks for your efforts here - it made the homebridge install process super simple. I played with homebridge on a rpi and since I am still using it, figure it is time to upgrade to something a little more stable long term. Truly appreciate your efforts on this!
