### ISSUE TITLE
multiple instances?

### ISSUE THREAD

**Issue by fugazzy** [oznu/homebridge-syno-spk#24]
Is there an easy way to use multiple instances of this SPK (use it more then once) or of multiple instances of Homebridge inside the docker image?

**Comment by oznu** [comment]
Hi @fugazzy,

This is not possible using the SPK.

The easiest way to do this, and manage in the future, would be to create a `docker-compose.yml` file and manage and run `docker-compose up -d` via the command line:

https://github.com/oznu/docker-homebridge#docker-compose

Alternatively you can create each instance one by one following the steps here:

https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology
