### ISSUE TITLE
DSM Update

### ISSUE THREAD

**Issue by CharlieSierra81** [oznu/homebridge-syno-spk#26]
Good evening,
I am facing issues after the latest DSM Update 6.2.2-24922-1:
Homebridge service cannot be started anymore. Any ideas? Thank you!

**Comment by oznu** [comment]
It's working on a fresh install of `6.2.2-24922`:

![image](https://user-images.githubusercontent.com/3979615/59396423-0b10b580-8dcc-11e9-9492-551f482d60fe.png)

I wasn't offered the `6.2.2-24922-1` update, but I manually updated:

![image](https://user-images.githubusercontent.com/3979615/59396599-e49f4a00-8dcc-11e9-9811-6375b9d84083.png)

I was able to removed the package after updating to `6.2.2-24922-1` and reinstalled it successfully.

**Comment by CharlieSierra81** [comment]
Thanks for the super quick response. I can confirm it is working. Re-installing did the job... No idea what happened.
