### ISSUE TITLE
"Multiple instance of Homebridge Found Installed"

### ISSUE THREAD

**Issue by mjgunn99** [oznu/homebridge-syno-spk#28]
I deleted a previous version of Homebridge that I had running on my Nas and installed this one, and I'm getting this error in the log occasionally.

2019-07-23 03:59:48,stdout,"[0;37m[7/22/2019, 11:59:48 PM] [0m[0;36m[Config][0m [0;33mMultiple Instances Of Homebridge Found Installed[0m
"
2019-07-23 03:59:48,stdout,"[0;37m[7/22/2019, 11:59:48 PM] [0m[0;36m[Config][0m [0;33m/homebridge/node_modules/homebridge[0m
"
2019-07-23 03:59:48,stdout,"[0;37m[7/22/2019, 11:59:48 PM] [0m[0;36m[Config][0m [0;33m/usr/local/lib/node_modules/homebridge[0m

Everything seems to be working fine, but any idea what I need to cleanup to stop this?

**Comment by oznu** [comment]
Remove this one `/homebridge/node_modules/homebridge`.

Do so by running this in the container:

`npm uninstall homebridge`

**Comment by mjgunn99** [comment]
Just tried that and I got this error

/homebridge # npm uninstall homebridge                                                                 
npm ERR! code ETARGET                                                                                  
npm ERR! notarget No matching version found for homebridge-nest@3.1.0                                  
npm ERR! notarget In most cases you or one of your dependencies are requesting                         
npm ERR! notarget a package version that doesn't exist.                                                
                                                                                                       
npm ERR! A complete log of this run can be found in:                                                   
npm ERR!     /root/.npm/_logs/2019-07-23T04_14_51_180Z-debug.log 

Assuming I did it right, I opened Docker, opened the homebridge container, went to Terminal, create with command SH, and then ran the command.

**Comment by oznu** [comment]
Is there a file named "package-lock.json" in your config directory? If so delete it and try again. Otherwise just manually delete `/homebridge/node_modules/homebridge`.

**Comment by mjgunn99** [comment]
Success!  No package-lock.json file I found (it should have been under /homebridge if I had it?) so I went ahead and deleted the homebridge directory and restarted the container, error message gone.  Thank you for the help, I didn't realize that when it said the directory was /homebridge/node_modules etc etc, it meant /docker/homebridge etc.

And since I have the man himself helping me with this (apparently) extremely simple problem I'd like to say thank you for this and everything else you've done with your homebridge projects.  I'm sure I'm like a lot of your users, just knowledgeable enough in this kind of stuff to muddle our way through and not break anything too bad thanks to how easy you've made it.

**Comment by oznu** [comment]
Thank you 😄.

The message is from the point of view inside the container, so in this case `/homebridge/node_modules` relates to `/volume1/docker/homebridge/node_modules` as you discovered - but the applications inside the container don't have visibility of this.

**Comment by andsoitgoes** [comment]
> Remove this one `/homebridge/node_modules/homebridge`.
> 
> Do so by running this in the container:
> 
> ```
> npm uninstall homebridge
> ```

Just wanted to reply and thank you - I migrated to another raspberry pi and couldn't figure this out, who knew it would be so easy.

And hands down, what you've done with Homebridge is so amazing, I feel so lucky to be alive with technology like this, and developers like you who care so much.

Thanks!
