### ISSUE TITLE
How to install plugin fork?

### ISSUE THREAD

**Issue by ChrisChiera** [oznu/homebridge-syno-spk#29]
When searching for plugins to install, for example the highly popular Homebridge-isy-js the main one shows, however that plugin for instance was abandoned years ago, but a fork has taken over as the main one. Homebridge-isy-js even links and recommends the fork in the release notes. But on this plugins search it only shows the original (the discontinued one) and don't see how to choose the fork that replaces it?

**Comment by oznu** [comment]
As per the fork read me:

```
npm install github:pradeepmouli/homebridge-isy-js
```

The author of the fork has not published the package to npm, so it won't show up in search results.

**Comment by oznu** [comment]
You can run that command via the UI's built in terminal.

Docker menu icon -> Terminal.

**Comment by ChrisChiera** [comment]
Thank you, that clarifies it!

**Comment by zhukovheorhii** [comment]
How to do the same for HB installed as a plugin via Plugin Center?

**Comment by oznu** [comment]
What is Plugin Center?

**Comment by zhukovheorhii** [comment]
Sorry, I mean Package Center at the Synology DSM

**Comment by oznu** [comment]
> Sorry, I mean Package Center at the Synology DSM

From the Homebridge UI Terminal:

```
pnpm add github:pradeepmouli/homebridge-isy-js
```

**Comment by zhukovheorhii** [comment]
thanks a lot
