### ISSUE TITLE
Since DSM 6.2.2-24922 Update 3 homebridge-syno-spk 1.0.7 is no longer running 

### ISSUE THREAD

**Issue by skynet74** [oznu/homebridge-syno-spk#30]
## Please see this issue for solution: https://github.com/oznu/docker-homebridge/issues/227

---
Since 08/28/2019 the homebrigde-syno-spk in version 1.0.7 is no longer running on Synology DSM. Synology Update DSM 6.2.2-24922 Update 3.

http://192.168.xx.xx:8581 can't connect. Still someone has the same problem?

Nico

**Comment by oznu** [comment]
Please see https://github.com/oznu/docker-homebridge/issues/227

The latest update to the Synology Docker app is broken.

**Comment by oznu** [comment]
Synology have released a new docker package that should have fixed this issue.
