### ISSUE TITLE
Config UI does not work out of the box

### ISSUE THREAD

**Issue by AxelTerizaki** [oznu/homebridge-syno-spk#31]
I just tried to install your SPK. Thank you for making it.

However, config UI X plugin doesn't seem to be installed by default. When you click on the Homebridge icon in the Synology menu it doesn't work.

I fixed it by adding `npm install homebridge-config-ui-x` to `startup.sh` and added the right platform to `config.json` manually. (I just followed the plugin's instructions)

Hope this'll help.

**Comment by AxelTerizaki** [comment]
Also I just noticed there was an environment variable for homebridge config but it seems set to 0 by default, maybe that's why I didn't get the config UI enabled?

**Comment by oznu** [comment]
Please take a look at https://github.com/oznu/docker-homebridge/issues/227.

**Comment by AxelTerizaki** [comment]
Oh I'm just unlucky then :) Thanks for the information, I'll close the issue.

**Comment by fugazzy** [comment]
Hello, I updated to the lasses docker (17.x to 18.x) on my Synology. I can't (re-)start any container anymore:
> OCI runtime create failed: container with id exists . . .
Did you have such issues? I could not find any hint by surching the net.
