### ISSUE TITLE
Cannot Install Homebridge on a DS212J with DSM 6.2.2-24922 Update 4

### ISSUE THREAD

**Issue by gilbert76** [oznu/homebridge-syno-spk#35]
Hello,

when I want to install hombridge-doke.spk I get the following Issues:

The package is not compatible with your Plattform or is not compatible with your DMS Version.
Cann you help me?

**Comment by oznu** [comment]
Hi @gilbert76,

This only works on devices capable of running the Synology Docker app.

https://www.synology.com/en-au/dsm/packages/Docker

DS212J does not appear on the supported device list?

**Comment by gilbert76** [comment]
Have you another method to install this package?

**Comment by oznu** [comment]
No. It won't run without Docker.
