### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by robiotik** [oznu/homebridge-syno-spk#38]
Hi, unfortunately I cannot install Homebridge on my Synology :/ Is it too old?
More information in the pictures

![Bildschirmfoto 2020-04-16 um 21 59 58](https://user-images.githubusercontent.com/37381800/79501166-e6115280-802d-11ea-87f0-ad114319e3de.png)
![Bildschirmfoto 2020-04-16 um 22 00 32](https://user-images.githubusercontent.com/37381800/79501179-ead60680-802d-11ea-8266-f6c55ade59ab.png)

**Comment by oznu** [comment]
Only devices compatible with the Docker package are supported.

https://www.synology.com/en-au/dsm/packages/Docker

This is generally models with Intel amd64 CPUs.
