### ISSUE TITLE
[Feature request] Allow configuration of the shortcut

### ISSUE THREAD

**Issue by piotrtobolski** [oznu/homebridge-syno-spk#39]
I have migrated from manual docker management and everything works fine for me, so thanks for the work on this app!

I have minor feature request. I would like the DSM shortcut pointing to the homebridge UI to be useful but I don't have its port exposed as I think this is good security practice to not expose its port or map it do different than the default one. I would like it to be configurable so I could provide my local IP (so it will work locally) and/or another port.

Thanks!

**Comment by oznu** [comment]
I did try this at some point a couple years ago without success.

If you want to have a go at it, this project uses the standard Synology Package SDK:

https://help.synology.com/developer-guide/
