### ISSUE TITLE
Can't connect to the UI

### ISSUE THREAD

**Issue by iRonin** [oznu/homebridge-syno-spk#4]
I've installed the package, it's running, when I click the icon a new tab with URL opens but it seems the server is not running. 
I had the package installed at the beginning of your development when I got the wizard and all, then uninstalled it and reinstalled today - no wizard and this. Should I remove some files or something? Maybe the config changed or whatever?

**Comment by oznu** [comment]
Thanks for raising the is. I've been testing the package with each new release of Docker and UI and it was working on my setup.

When you say you got no wizard, do you mean you weren't asked where to store the homebridge config and if you would like to install the UI?

**Comment by iRonin** [comment]
> When you say you got no wizard, do you mean you weren't asked where to store the homebridge config and if you would like to install the UI?

Yes, the package installed, started, no wizard was shown, when I click the icon to launch it nothing happens.

**Comment by iRonin** [comment]
I'm reinstalling it and now I can see the wizard.

**Comment by iRonin** [comment]
Got it running. What's the credentials? :)

**Comment by oznu** [comment]
admin/admin

It's on my to-do list to add this info to the docs or maybe the install wizard.

**Comment by oznu** [comment]
Fixed in 1.0.5. Default credentials are advised during install wizard. Also enabled a flag that should prevent installation without the wizard being shown (aka silent installs).

**Comment by iRonin** [comment]
I've got it running but I cannot sign in - what are the credentials? My NAS ones do not work.

**Comment by iRonin** [comment]
Thank you!

**Comment by iRonin** [comment]
I love the UI, it's great!
