### ISSUE TITLE
Migrate to this from old docker install

### ISSUE THREAD

**Issue by dppeak** [oznu/homebridge-syno-spk#40]
What is the proper method of migrating from the [old method](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology) to using this?  This method seem to be easier to update.

I've tried installing this and hoping it would see my existing files (plugins and config).  However, once installed, this process will not launch and I can't determine the reason.

Thanks,
Dave

**Comment by oznu** [comment]
Hi @dppeak, as long as you enter the storage path of your current Homebridge setup during the install wizard this should just replace your existing setup.

If you're old container is not named "homebridge" you may need to delete it manually.

**Comment by dppeak** [comment]
Okay, must have just been a timing issue as it's working now.  

However, the next question I have is, how do I update the update the container (node update, etc) with this new method?  Do I still have to go through Docker and download new image, stop old container, copy settings, etc (as shown [here](https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-Synology))

**Comment by dppeak** [comment]
Uninstalled and then reinstalled and it's working as it should.  Thanks for providing this.  It's much easier now to update the container.
