### ISSUE TITLE
No SSL

### ISSUE THREAD

**Issue by marcoheijkoop** [oznu/homebridge-syno-spk#42]
Hi,

Is it possible to use SSL with the Synology package?

Best regards,

Marco

**Comment by oznu** [comment]
@marcoheijkoop 

See https://github.com/oznu/homebridge-config-ui-x#enabling-ssl for config options to setup SSL with your own certificate. You will need to make the certificates available to the container - probably by putting them in the `/homebridge` volume mount.

**Comment by marcoheijkoop** [comment]
Ok.

I did that today but i think i made a mistake.
I made a new map and put the certificate in that map.
So need to put theme in the root of the directory?

**Comment by oznu** [comment]
If you don't already have a config block for the UI in your config.json; go to the UI and in the top right corner use the drop down menu and select "UI Settings". Open the modal and just click save. This will add some default UI config to the `config.json`, and where the `ssl` option should live.

> So need to put theme in the root of the directory?

If you put your key and cert file in the same folder as the homebridge `config.json`, you would reference them like this:

```json
      "ssl": {
        "key": "/homebridge/privkey.pem",
        "cert": "/homebridge/fullchain.pem"
      }
```

**Comment by marcoheijkoop** [comment]
Needed to convert my key and cert to pem format.
And then added the below settings in mine "name": "Config" part

`      "ssl": {
        "key": "/homebridge/privkey.pem",
        "cert": "/homebridge/fullchain.pem"
      }`

And is working now. Thanks
