### ISSUE TITLE
Cant install on DS420+ with DSM6.2.3

### ISSUE THREAD

**Issue by RainbowLinLin** [oznu/homebridge-syno-spk#43]
Hi I cant install homebridge-syno-spk on my DS420+
My DSM version is 6.2.3
![image](https://user-images.githubusercontent.com/12733616/82152129-e3ef1d80-9891-11ea-93c3-7a9376e0ac63.png)

**Comment by oznu** [comment]
Are you able to install the Docker app?

**Comment by whw313** [comment]
> Are you able to install the Docker app?

Yes, I have the same problem.

I can install Docker app, version is 18.09.0-0513, can't install homebreidge-syno-spk on DS420+, DSM 6.2.3.

**Comment by MyungHunPark** [comment]
i have same problem, too.
DS220+, DSM 6.2.3.
homebridge-syno-spk 1.2.0, 1.1.0, 1.0.7, 1.0.6

`{error: {code: 4528}, success: false}`

**Comment by kwalb** [comment]
Can confirm issue is the same on a DS920+

**Comment by THX723** [comment]
@oznu The new DSxx20 are based on _Gemini Lake_ CPUs. Will need to include "geminilake" architecture in the INFO file.
After making the change and repacking the .spk, I was able to install without any issues on my DS920+

**Comment by oznu** [comment]
Thanks for figuring this out @THX723.

Could you make a PR with the changes that worked for you?

**Comment by THX723** [comment]
@oznu I think it's a bit more involved to update the source code. The quick fix I did was to simply untar the .spk, edited the INFO file (as follows), and then re-tar.

from:
```
arch="x86 bromolow cedarview avoton braswell broadwell dockerx64 kvmx64 grantley denverton apollolake broadwellnk"
```
to:
```
arch="x86 bromolow cedarview avoton braswell broadwell dockerx64 kvmx64 grantley denverton apollolake broadwellnk geminilake"
```


`INFO.sh` in the source code has pointer reference `$(pkg_get_unified_platform)` that I'm not familiar with.
```
source /pkgscripts/include/pkg_util.sh
...
arch="$(pkg_get_unified_platform)"
```

Do you know where source `pkg_util.sh` is from? Is that part of the Synology Toolkit?

**Comment by oznu** [comment]
We can probably replace `$(pkg_get_unified_platform)` with the string of platform.

**Comment by THX723** [comment]
@oznu Okay easy enough then. I'll create a PR.

**Comment by oznu** [comment]
Thanks, 1.3.0 is building now. Are you able to test it once it's done? You can upload it over an existing install without loosing any settings.

**Comment by THX723** [comment]
@oznu file name for the new build is incorrect. Looks like it's referencing the version attribute, which also needs to be updated.

**Comment by oznu** [comment]
I'll fix that.

May I ask where you got this list of architectures from @THX723?

**Comment by THX723** [comment]
@oznu Here's there reference: https://github.com/SynoCommunity/spksrc/wiki/Architecture-per-Synology-model

**Comment by oznu** [comment]
I might just use `noarch`.

https://github.com/openhab/openhab-syno-spk/blob/master/INFO#L7

The "Docker" dep will stop it being installed on non-Docker platforms.

**Comment by oznu** [comment]
1.3.0 released.

**Comment by THX723** [comment]
@oznu Perfect. I was about to suggest `noarch` as a possible/better alternative.
