### ISSUE TITLE
The format of HomebridgeDocker-86x....spk file is invalid

### ISSUE THREAD

**Issue by oZora1337** [oznu/homebridge-syno-spk#44]
When trying to add the image as file in docker (synology), I receive the mentioned error message.

This is after I deleted another version of the .spk which I was able to select. Can you guys help me adding the image?

I tried uninstalling docker and re-installing it but that did not bring any help.

Thanks

**Comment by oznu** [comment]
Try https://github.com/oznu/homebridge-syno-spk/releases/tag/1.2.0

I just confirmed it still works on a fresh install of DSM DSM 6.2.2-24922.

**Comment by oZora1337** [comment]
Been trying with 1.2.0, with 1.1.0, with 1.0.7.. everytime receiving the same error. I believe something is wrong somewhere else.

Is there any registry that I would need to delete, even after I uninstalled Docker?

Thanks for replying that fast, much appreciated.

**Comment by oznu** [comment]
You could try restart DSM, one user on Discord said that allowed them to install the package.

**Comment by oZora1337** [comment]
Thanks.

**Comment by oznu** [comment]
Did that work?
