### ISSUE TITLE
How to uninstall Homebridge Docker on synology?

### ISSUE THREAD

**Issue by SteveW25561** [oznu/homebridge-syno-spk#47]
My Synology Docker application won't run currently after the new DSM update - I am going to try and uninstall Docker and reinstall it but want to keep all my Docker container configurations, etc.

When I go to uninstall Docker it says "Homebrdige Docker is dependent on this package. Please uninstall Homebridge Docker first before uninstalling the package" - but I can't see the Homebridge Docker app in the installed packages directory.

Is there a way to uninstall the pkg yet keep my Homebridge configuration working after reinstalling Docker? I don't want to redo all the setup of Homekit/Homebridge especially with all the automations I have made.

I'm hoping I can just remove the pkg and the Docker container config will still survive - I presume this pkg makes the docker compose for the user, but afterward it isn't needed and removing won't affect the container?

**Comment by oznu** [comment]
Do a backup first.

https://github.com/homebridge/homebridge/wiki/Backup-and-Restore

**Comment by SteveW25561** [comment]
Thankfully I did a backup months ago but I can't run Docker currently on my Synology to get a new backup today (which is why I'm trying to uninstall/reinstall Docker). 

I have SSH access, what steps do I need to do to manually uninstall the homebridge docker pkg since it doesn't appear on the installed apps GUI in DSM?

**Comment by oznu** [comment]
Uninstalling Docker won't delete your homebridge config. You can safely remove it.

**Comment by BeKs1968** [comment]
Hello,
i want to delete Homebridge totally. 
So, that next time ill install it, no Homebridge is actually to see.
I want to do a flesh install.
How can i do it?

**Comment by merlinbk** [comment]
I'm trying to uninstall Docker but the package center says Homebridge is dependent on this package. "Please uninstall  Homebridge first before uninstalling this package." I uninstalled Homebridge in 2021. How do I find what this is referring to? How can I remove it?
