### ISSUE TITLE
have to reinstall if docker share is moved

### ISSUE THREAD

**Issue by yahms** [oznu/homebridge-syno-spk#48]
probably not a major issue, but the full path to the homebridge config is specified at install using absolute paths ie /volume1/docker/homebridgeconfig

if the shared folder that hosts the config is moved to another volume on the synology, the container doesnt start.

is it possible to put that in an environment variable, or make it easier to change after the fact? or is the docker / container ethos to blow it away and rebuild when changes are needed, if so then ignore :)

Workaround --
1. remove the homebridge package (this should leave the homebridge config in place - backup anyway before u do this !)
2. do the install again with the .spk file downloaded
3. at install, specify the volume where the docker share is now ie /volume1 or volume2 or volume3 etc

**Comment by oznu** [comment]
The container would get recreated by docker-compose if the volume path changed anyway. Removing the package and re-installing only take a minute 😄
