### ISSUE TITLE
Visible via Bonjour but can't connect to HomeBridge

### ISSUE THREAD

**Issue by vincbic** [oznu/homebridge-syno-spk#5]
Thank you for your work on this!

I'm having an issue to connect to HomeBridge on the Home app. 
I can't properly diagnose why, the logs look fine, no errors. The ports are not blocked by the firewall, I also see it when I do a lookup on Bonjour (_hap._tcp.). But I do not see it on the Home app, and scanning the QR Code brings an error.

Any idea on what I might be missing?

**Comment by oznu** [comment]
Try changing the username in the config to something else, delete the `accessories` and `persist` folders that will be in your homebridge config directory and restart Homebridge.

When picking a new username make sure you only use [hexadecimal](https://en.wikipedia.org/wiki/Hexadecimal) characters.

**Comment by vincbic** [comment]
Solved, thank you!
