### ISSUE TITLE
Unable to connect Homebridge to Apple Home

### ISSUE THREAD

**Issue by pixelrogue1** [oznu/homebridge-syno-spk#58]
Yes, this topic has been discussed a fair amount and while there are 100's of things to try it feels like I have tried all of them twice.

**ENVIRONMENT**
- Synology running DSM7.0
- iPad Mini 14.3
- Docker 20.10.3-1233
- Homebridge container (oznu/latest)
- Firewalls and VPNs disconnected on all devices
- Bonjour disabled

**CURRENT STATE**
- Homebridge is up and running as expected
- Homekit is up and running as expected
- Failure when adding homebridge to HomeKit.
--- Homekit > add accessory > Scan or enter code > bridge icon displays -select add to home > spins to time out.
      Accessory not found. On occasion an error that reads wrong code

**EXPERIMENTS INCLUDE**
- Bypassed the default Share Host to open ports 5036/51827/5353/8531 on Synology
- Adding PUID and PGIDs to compose
- Changing username to replicate MACID
- Various reboots/reinstalls of all devices
- Using different networks
- Proximities to various devices (router/hub/synology/iPad etc)

**OBSERVATIONS INCLUDE**
- does not appear homebridge has been assessed an IP address nor published ports

**Comment by skrollme** [comment]
Did you find the cause of the problem, @pixelrogue1 or @sev101 ? I'm facing the same problem

**Comment by pixelrogue1** [comment]
Closest I have is that it is related to the cell phone connection…t-mobile off shore support so no not know what to do .. awaiting am engineering ticket response Sent from my digital implant....On Nov 27, 2022, at 1:44 PM, Sebastian K ***@***.***> wrote:﻿
Did you find the cause of the problem, @pixelrogue1 or @sev101 ? I'm facing the same problem

**Comment by pixelrogue1** [comment]
Responded to wrong post. Gave up, as it was Wink and even though we laid the ransom they locked us out of the API for HomeBridge so switched to native homekit. Sent from my digital implant....On Nov 27, 2022, at 2:01 PM, Peter Robberts ***@***.***> wrote:﻿Closest I have is that it is related to the cell phone connection…t-mobile off shore support so no not know what to do .. awaiting am engineering ticket response Sent from my digital implant....On Nov 27, 2022, at 1:44 PM, Sebastian K ***@***.***> wrote:﻿
Did you find the cause of the problem, @pixelrogue1 or @sev101 ? I'm facing the same problem
