### ISSUE TITLE
Allow to pass parameters to the command line

### ISSUE THREAD

**Issue by iRonin** [oznu/homebridge-syno-spk#6]
I need to run a plugin in a debug mode - would be great to provide command line params, eg.

```
DEBUG=homebridge-weather-station-extended
```

**Comment by oznu** [comment]
This would be set as an environment variable. I don't think adding such an option to the install wizard would be useful, but you can easily add it via the DSM GUI:

1. Go to the Docker app
2. Stop the Homebridge container
3. Edit the container and go  to the Environment tab
4. Add environment variable
5. Save and start container

![image](https://user-images.githubusercontent.com/3979615/35133556-f046e26c-fd24-11e7-98ba-3975926363ef.png)
