### ISSUE TITLE
sudo pass

### ISSUE THREAD

**Issue by kalety** [oznu/homebridge-syno-spk#61]
Hi! Thank you for your work!.
which is the sudo password In Homebridge Terminal?

Thanks in advance!

**Comment by oznu** [comment]
On DSM 7.0 the service user does not have sudo permissions or even a password. This is a Synology managed service user with very restrictive access as per DSM 7.0 package requirements.

If you need to perform actions that require additional permissions, you will need to SSH to your NAS using your regular DSM credentials.
