### ISSUE TITLE
connexion to server impossible

### ISSUE THREAD

**Issue by stephaneaudran** [oznu/homebridge-syno-spk#62]
Hi, I run DSM 7 on a syno DS713+, I don’t know if it’s a X86 chip.

Homebridge took forever to install, then I can’t open it, I’ve got the message «  connexion to server impossible »….

I also have a 1819+ in another location, and it works just fine on it.

Is it a compatibility issue ?

Thanks

**Comment by oznu** [comment]
Perhaps, I don't know if it's just the CPU is to low power to complete the install (which is pretty cpu intensive since it pulls down the packages from npm) or just general comparability.

It's very hard to test/debug this, as I really only have access to a modern x86_64 unit.

**Comment by stephaneaudran** [comment]
The problème comes from the NAS, very slow.
I stopped indexing, but it’s still cleaning drives .
I often lose connexion to DSM, and have to reboot the NAS.
This is what I had to do this morning as I couldn’t connect to DSM once again, and for the first time, I ‘ve been able to launch Homebridge !  I still have an issue to upgrade it, the admin page shows 78% cpu usage.
But it works ! Thanks for your help .

**Comment by oznu** [comment]
I purchased a DS120j (MARVELL Armada 3720 88F3720) just to test this, which is the cheapest and slowest NAS in the synology line up, and it does work.

**Comment by stephaneaudran** [comment]
> 

Yes, I don’t know what’s wrong with mine, maybe a problème with a disk, as I have an DX517 expansion unit , and mixed old / new disks. No problem found with smart tests , but still slow, even after a reset and reinstall of DSM …

**Comment by oznu** [comment]
CPU does burst to 100% while restarting the UI, but settles does to 4% load total on the DS120j.
