### ISSUE TITLE
libfdk_aac is not installed?

### ISSUE THREAD

**Issue by morginq** [oznu/homebridge-syno-spk#63]
Getting error that libfdk_aac is not installed for ffmpeg. Works if installed as a docker image, but not when using DSM7 package.

**Comment by oznu** [comment]
Ffmpeg is not provided by the DSM7 package.

Homebridge will use DSM's own ffmpeg binary if the plugin isn't providing it's own version.

**Comment by oznu** [comment]
This might help: https://synocommunity.com/package/ffmpeg

**Comment by morginq** [comment]
Is it possible to use a backup /restore generated backup from within the DSM7 package to restore into your docker of homebridge?

**Comment by oznu** [comment]
Yes

**Comment by oznu** [comment]
https://github.com/oznu/homebridge-syno-spk/releases/tag/2.2.1 

+ 

https://github.com/oznu/homebridge-syno-spk/wiki/DSM-7:-ffmpeg-with-libfdk_aac
