### ISSUE TITLE
Advice on moving from Docker-based Homebridge to non-Docker version

### ISSUE THREAD

**Issue by bjornand1** [oznu/homebridge-syno-spk#66]
Hi, I have quite an elaborate Homebridge setup running in Docker on my Synology DS720+, and hope someone can answer a few questions about possibly updating it to the non-Docker version?

- What, if any, are the benefits of moving Homebridge out of Docker?
- If deciding to update, it seems the old Docker instance must first be removed (to open port 8581), and that scares me deeply considering how much work it would take if all Homebridge devices must be set up again in HomeKit. So out of ignorance, I ask if there are sure-fire ways to copy the config and any other required files from Docker to the new install so that devices and their automations in HomeKit remain as they are?

**Comment by oznu** [comment]
Do a backup and restore. It retains everything.

**Comment by bjornand1** [comment]
@oznu, just to make sure I fully understand this before pushing the button; the sequence of steps will be:

- In the Homebridge UI, create a backup
- Remove the Docker package
- Install the non-Docker package
- Start Homebridge
- Restore from the backup

And in the meantime, when Homebridge is not running, the often finicky HomeKit won't determine that these devices have been removed and scrap them?

**Comment by oznu** [comment]
Correct.

**Comment by bjornand1** [comment]
Thanks again, this seems to work, BUT Homebridge won't start due to this error:

[1/31/2022, 10:57:19 AM] Error: EACCES: permission denied, mkdir '/homebridge'

Not really sure how to fix this?

**Comment by oznu** [comment]
From Docker?

**Comment by bjornand1** [comment]
The error comes when starting the non-Docker installation, and I see that there is one instance of such a path in the config:

"videoProcessor": "/homebridge/node_modules/homebridge-camera-ui/node_modules/ffmpeg-for-homebridge/ffmpeg"

What should I change this to?

**Comment by bjornand1** [comment]
Ah, then I see that the folder node_modules is completely empty in the non_docker folder

**Comment by oznu** [comment]
Just remove it.

**Comment by oznu** [comment]
Note you may need to install ffmpeg on Synology as per readme.

**Comment by bjornand1** [comment]
OK, removed that line, but I still get the same access error message. Now installing ffmpeg per readme.

**Comment by bjornand1** [comment]
Installing ffmpeg did not help, and I cannot find another config line that has a path to homebridge... Kinda stuck here.

**Comment by bjornand1** [comment]
But it seems to be related to the Camera UI plugin, after disabling it, Homebridge starts and all devices are back!

**Comment by cirrusflyer** [comment]
Thinking of doing the same.  This question wasn't answered I don't believe:

"What, if any, are the benefits of moving Homebridge out of Docker?"
