### ISSUE TITLE
if plugin requires certain root access commands like ping

### ISSUE THREAD

**Issue by kheewei** [oznu/homebridge-syno-spk#67]
Hi, I understand that in DSM7, Synology does not allow 3rd party apps to access root user. I am not very technical, but is there a way to allow certain commands to be enabled for the default user "homebridge" either by the User ID, User Name, or the UID (which, in my setup it seems to be 108668 for both times I manually installed the spk)? 

This is for certain plugins that may require some simple commands like ping and net rpc, both used in my WOL setup. 

Thanks!

**Comment by kheewei** [comment]
Ok, less than 24 hours later, I found this, which I guess is generally how certain access/commands are granted to non-root users, someone please correct me if I'm wrong. 

1. Create/edit a file in this path:
sudo nano /etc/sudoers.d/{any_filename}

2. Put in the required commands to be delegated to "homebridge" user id (without requiring password):
Cmnd_Alias PING = /usr/bin/ping
homebridge ALL=(root) NOPASSWD: PING

3. This configuration will require "sudo" (not sure if there is a way to make it so that it's not required), e.g.:
sudo ping -c 1 <IPaddress>

**Comment by johnnygoodface** [comment]
I've got the same question : I suspect the peoplex plugin is not working because it can't ping from HB on DSM7 too (that seams to be using a Ping command to determine the presence of someone). Anyone?

**Comment by johnnygoodface** [comment]
The pluginx programmer says he doesn't have access to a NAS to test anything. So until he does, I guess we'll have to really on another approch/solution/plugin

**Comment by oznu** [comment]
Synology DSM does not allow native packages to run any privileged commands. If your device supports it, you should try Docker instead.
