### ISSUE TITLE
FFmpeg, Unknown encoder 'libfdk_aac'

### ISSUE THREAD

**Issue by alexmb2020** [oznu/homebridge-syno-spk#68]
Hi
Installed homebridge-syno-spk on Synology Intel based DS216+ using backup and restore from Docker version.
All looks good except “Homebridge Camera FFmpeg”, 
First was no screenshot, no stream in homekit.
Installed “FFMPEG update”, have screenshot but no video. 
After disabling audio have screenshot and video stream works but no audio of course.
If audio is enabled no video stream and errors in homebridge:
 [Camera FFmpeg] [Front camera] [fatal] Unknown encoder 'libfdk_aac'
 [Camera FFmpeg] [Front camera] FFmpeg exited with code: 1 and signal: null (Error)

Missing 'libfdk_aac' encoder? Is any simple method to install it?
Thank you!

**Comment by oznu** [comment]
See https://github.com/oznu/homebridge-syno-spk/wiki/DSM-7:-ffmpeg-with-libfdk_aac

**Comment by alexmb2020** [comment]
Thank you for reply, Yes I did it, few min ago reinstalled one more time, but the same errors:
[Camera FFmpeg] [Front camera] [fatal] Unknown encoder 'libfdk_aac'
[Camera FFmpeg] [Front camera] FFmpeg exited with code: 1 and signal: null (Error)
