### ISSUE TITLE
cannot update node & Npm

### ISSUE THREAD

**Issue by macjoeaustria** [oznu/homebridge-syno-spk#70]
When I try to start an update in the console, the following message appears:

_**We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

Password:**_ 

no password works!

kr

**Comment by johnnygoodface** [comment]
I've noticed that hovering the mouse over the node.js version offers the option to update node.js to the next version. You could try it like that maybe
<img width="267" alt="Capture d’écran, le 2022-02-14 à 10 53 38" src="https://user-images.githubusercontent.com/24813857/153898510-1e45296e-12c4-4fa1-b296-dfe2a98aba3f.png">

**Comment by macjoeaustria** [comment]
If I understand correctly, the update of the node is only possible via a general update of the homebridge program. thus only via the homebridge programmer for DMS 7 aka ONZU. a user cannot update it himself.
is that correct? the problem is that various plugins don't want to work with the outdated nodes.

**Comment by johnnygoodface** [comment]
Honesly I'm scared to click on "Update Available" I guess. I would know how to fix a node.js issue if running this "update" would screw up not only Homebridge, but my NAS also. For example I use "Synology Drive" and I know it uses node.js, but the v12 packaged, not the v16 Homebridge seems to be using. So in a nutshell, there seems to be 2 versions of Node.js on my NAS and I can't figure out where they are located and how to fix'em if anything would go wrong. :(

**Comment by wmar** [comment]
Back to "no password work" issue under Homebridge terminal! Any one have same issue and resolution on it?

Beside the node.js, how about npm update?

**Comment by dppeak** [comment]
Are you trying to su or sudo to do the update?  If so, the reason is that the 'homebridge' user is set up with a nologin shell for security.

**Comment by wmar** [comment]
Yes.  it shall be su or sudo related for update or add other support.

**Comment by dppeak** [comment]
The recommended path for updates for Node, would be to update the package. It looks like v2.2.2 is now out with updated Node of v16.14.0.

**Comment by johnnygoodface** [comment]
And how should I update it on a NAS? Using SSL? With what command please? sudo hb-service update-node? And would updating the node to 16.14 would impact the current Node 12 packaged from the NAS itself (used for Synology Drive App)?

**Comment by johnnygoodface** [comment]
nobody?

**Comment by julicuq** [comment]
Same issue here, is there a way to update through Homebridge terminal?

**Comment by johnnygoodface** [comment]
Why Oznu is not helping us? I sent him an email directly, and anything back.. We're all stuck at the same level here. Please Oznu, do something. Thx

**Comment by oznu** [comment]
Node 16.14.2 is available in v2.2.3 - you can do an in place upgrade.

**Comment by iceage2609** [comment]
@johnnygoodface I have the exact same problem , did you find any solution ? it's really frustrating , i got a plugin out of date and it needs a node update to work but i can't sudo update because i have no password to do it ?  Maybe @oznu has a way to do it.

**Comment by iceage2609** [comment]
> Node 16.14.2 is available in v2.2.3 - you can do an in place upgrade.
> 
> https://github.com/oznu/homebridge-syno-spk/releases/tag/2.2.3

Oh i just saw your post, thanks. We have to do the update from the homebridge UI or through our NAS menu ?

Thanks in advance

**Comment by oznu** [comment]
Download the package and "Manual Install" via DSM again. You do not need to uninstall the package first, you it will do an "upgrade".

**Comment by iceage2609** [comment]
> Download the package and "Manual Install" via DSM again. You do not need to uninstall the package first, you it will do an "upgrade".

Thanks a million. I am on it . And a last question, as far as i am concerned there is no way (for this type of installation without docker ) to set a password so we can sudo through terminal ?
 I guess the reason is what another user said that "the reason is that the 'homebridge' user is set up with a nologin shell for security. That is why you can't enter a password because one doesn't exit. That user is not allowed to login, just have processes run under it"

**Comment by oznu** [comment]
No, Synology does not allow packages to have any privileged access as of DSM7. The latest package has a notice on the sudo command letting you know this.

**Comment by oznu** [comment]
As of homebridge-config-ui-x 4.43.0-test.1 you can update Node.js using `hb-service update-node`.

https://github.com/oznu/homebridge-config-ui-x/wiki/How-To-Test-Upcoming-Changes

**Comment by johnnygoodface** [comment]
Can't wait for the new and improved 4.43 version :) Thx oznu

**Comment by johnnygoodface** [comment]
Just tried the **hb-service update-node** command and it worked wonderfully :)
<img width="728" alt="image" src="https://user-images.githubusercontent.com/24813857/167964573-757bc419-b463-41cd-85a7-0657c19364d9.png">
