### ISSUE TITLE
rebuild for DSM6.x,maybe more bug,need test

### ISSUE THREAD

**Issue by tbc0309** [oznu/homebridge-syno-spk#77]
https://github.com/tbc0309/homebridge-syno-spk/blob/master/homebridge-braswell-2.2.2-DSM6.spk
https://github.com/tbc0309/homebridge-syno-spk/blob/master/homebridge-rtd1296-2.2.2-DSM6.spk

**Comment by oznu** [comment]
1.3.0 works for DSM 5/6.

https://github.com/oznu/homebridge-syno-spk/releases/tag/1.3.0

To accept an update to use the native style for DSM 6 I'll need source code.
