### ISSUE TITLE
Backup tar.gz does not contain full "storage" directory

### ISSUE THREAD

**Issue by Cristov9000** [oznu/homebridge-syno-spk#79]
I am attempting to migrate from an Synology 918+ where Homebridge is a spk package install via Synology package center manual install, to a Synology 1221+ and run Homebridge in docker.  The docker instance will not accept the backup tar.gz created by the spk package install of Homebridge on the 918+.  I get "Uploaded file is not a valid Homebridge Backup Archive."  The docker instance will accept backups created by itself, but not backups created by the package instance from the 918+.

I unpacked the backups and it appears that the backups created by the package install on the 918+ only contain a shortcut/pointer to "storage" and not the full directory.  Where the backups created by the docker instance on the 1221+ contain a folder "storage" with the full file directory.  I am assuming that the lack of full directory is why the docker Homebridge will not accept the backup.  Was this an change made between versions? 

My install of the Synology package center version includes an older version of node , v16.13.2, than the docker install, v16.14, but there is no clear way to update the package in Synology package center.  Other than that I cant find any differences.  Is there a way to get backup and restore to work?

**Comment by oznu** [comment]
Should be fixed in 2.2.3 - you can do an in place upgrade.
