### ISSUE TITLE
Very fresh automator with DS218+

### ISSUE THREAD

**Issue by rgrtht** [oznu/homebridge-syno-spk#80]
I get a non-specific error at the end of installation process. Package Centre then tells me to uninstall. I can get no further.

I'm trying with 2.2.4 (x86_64) on a DS218+ (Celeron J3355 Apollolake).

Many thanks for your time :)

Edit: Apologies if this is not the right avenue for support... I'm also pretty fresh at GitHub (just in case it's not obvious 😬 )

**Comment by oznu** [comment]
Please try v3.0.0, the install process is a little less cpu intensive now and should handle low power devices better:

https://github.com/oznu/homebridge-syno-spk/releases/tag/3.0.0
