### ISSUE TITLE
Homebridge user interface is not loading

### ISSUE THREAD

**Issue by cristian5th** [oznu/homebridge-syno-spk#81]
Hello.

After installing the Homebridge package on a Synology DS418, the user interface webpage cannot be accessed. The error states that the server cannot be found. I have other applications in the same server with different ports and they are all reachable except the Homebridge.

Please note that this is a DS without Docker.

I have DSM 7.0.1-42218 and I installed the armv8 package of the homebridge-syno.

Any idea about what configuration can I touch to make it work?

**Comment by oznu** [comment]
Please try v3.0.0, the install process is a little less cpu intensive now and should handle low power devices better:

https://github.com/oznu/homebridge-syno-spk/releases/tag/3.0.0

**Comment by cristian5th** [comment]
I don't see the armv8 version for download. Should I install the armada37xx for the DS418?

**Comment by oznu** [comment]
If you add the package source it will grab the correct one automatically. Otherwise grab the rt1296 variant.

**Comment by janmey-meja** [comment]
Hello I have a DS918+ with DSM7.0.1 running. 
I have the same issue that I not be able to access the UI, on http://MY-DSM-IP:8581 
Also I can't connect it with HomeKit despite the credentials provided inside the homebridge.log file. 
DSM shows Homebridge as running and I can see it as homebridge 7016 **** inside the HomeKit app but connection is also there timing out.

attached the homebridge.log file: (*******replaced the pairing code with stars *******) 
maybe that tells you something ;-)  as I am clueless to coding 

[37m[5/1/2022, 10:27:37 AM][0m [36m[HB Supervisor][0m Creating default config.json: /volume1/homebridge/config.json
[37m[5/1/2022, 10:27:37 AM][0m [36m[HB Supervisor][0m OS: Linux 4.4.180+ x64
[37m[5/1/2022, 10:27:37 AM][0m [36m[HB Supervisor][0m Node.js v16.15.0 /volume1/@appstore/homebridge/app/bin/node
[37m[5/1/2022, 10:27:37 AM][0m [36m[HB Supervisor][0m Homebridge Path: /volume1/homebridge/node_modules/homebridge/bin/homebridge
[37m[5/1/2022, 10:27:37 AM][0m [36m[HB Supervisor][0m UI Path: /volume1/homebridge/node_modules/homebridge-config-ui-x/dist/bin/standalone.js
[0;37m[5/1/2022, 10:27:43 AM] [0m[0;36m[Homebridge UI][0m [0;33mHomebridge Config UI X v4.43.2 is listening on :: port 8581[0m
[37m[5/1/2022, 10:27:43 AM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -I -P /volume1/homebridge/node_modules --strict-plugin-resolution
[37m[5/1/2022, 10:27:43 AM][0m [36m[HB Supervisor][0m Started Homebridge v1.4.1 with PID: 27776
[0;37m[5/1/2022, 10:27:43 AM] [0m[0;36m[Homebridge UI][0m [0;33mAdded new user: admin[0m
[0;37m[5/1/2022, 10:27:43 AM] [0m[0;36m[Homebridge UI][0m Username and password have been set to default:
[0;37m[5/1/2022, 10:27:43 AM] [0m[0;36m[Homebridge UI][0m Username: admin
[0;37m[5/1/2022, 10:27:43 AM] [0m[0;36m[Homebridge UI][0m Password: admin
[37m[5/1/2022, 10:27:45 AM] [39mLoaded config.json with 0 accessories and 1 platforms.
[37m[5/1/2022, 10:27:45 AM] [39m---
[37m[5/1/2022, 10:27:45 AM] [39mLoaded plugin: homebridge-config-ui-x@4.43.2
[37m[5/1/2022, 10:27:45 AM] [39mRegistering platform 'homebridge-config-ui-x.config'
[37m[5/1/2022, 10:27:45 AM] [39m---
[37m[5/1/2022, 10:27:45 AM] [39mLoading 1 platforms...
[37m[5/1/2022, 10:27:45 AM] [39m[36m[Config][39m Initializing config platform...
[37m[5/1/2022, 10:27:45 AM] [39m[36m[Config][39m Running in Service Mode
Setup Payload:
X-HM://0024EZS54DNI1
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
[30m[47m                       [49m[39m
[30m[47m    ┌────────────┐     [49m[39m
[30m[47m    │ ************************************************
[30m[47m    └────────────┘     [49m[39m
[30m[47m                       [49m[39m
[37m[5/1/2022, 10:27:45 AM] [39mHomebridge v1.4.1 (HAP v0.10.2) (Homebridge 7016) is running on port 51735.

**Comment by oznu** [comment]
Do you have the Synology firewall enabled by any chance?

**Comment by janmey-meja** [comment]
disabled temporarily the firewall, and now can access the UI

**Comment by oznu** [comment]
Make a rule for 8581/tcp and whatever port homebridge is running on /tcp.
If you create any child bridges you'll need to open the port they are assigned too.

**Comment by oznu** [comment]
It looks like I can have the package automatically open the port. The homebridge port is dynamically assigned so that could be tricky to manage.

**Comment by janmey-meja** [comment]
that would be great - I will open 8581 for now to access the UI and the other service port you say will change  at least after a restart ??

**Comment by cristian5th** [comment]
I confirm. Version 3 is working properly on the DS418.

Thanks a lot.

**Comment by oznu** [comment]
>  and the other service port you say will change at least after a restart ??

The homebridge port (found in the config file) is assigned on first launch, it won't change by itself.

**Comment by janmey-meja** [comment]
Great I added that too.  

Thanks a lot - that was the fastest response and problem solving I ever got. ;-)

**Comment by oznu** [comment]
Added a note to the readme / wiki about checking the firewall after installation.
