### ISSUE TITLE
Lost all plugins with update to 3.0.0

### ISSUE THREAD

**Issue by rh295** [oznu/homebridge-syno-spk#82]
Added the Homebridge Synology Package Source on my DS1821+ with DSM 7.0.1 and do the automatic update from package center. After restart Homebridge lost all plugins. Search for plugins for reinstall led to error messages. I then downloaded and installed version 3.0.0 manually, after which the search and installation of plugins worked again. What could have gone wrong ?

**Comment by oznu** [comment]
The release notes for 3.0.0 state:

> ### Breaking Changes
> Version v3.x.x contains breaking changes for users upgrading from v2.x.x or earlier. Plugins will require re-installation. > > You should [create a backup](https://github.com/homebridge/homebridge/wiki/Backup-and-Restore) before upgrading.

**Comment by rh295** [comment]
oh sorry, i missed that
