### ISSUE TITLE
config.json NOT generated after installing homebridge app through Synology DSM

### ISSUE THREAD

**Issue by wingmyway** [oznu/homebridge-syno-spk#83]
**Describe The Bug:**

config.json NOT generated after installing homebridge app through Synology DSM

Homebridge folder has been created, however, there is no config.json file generated at the folder
<img width="973" alt="image" src="https://user-images.githubusercontent.com/8107509/166132365-d36794b9-e773-4037-9d73-f7a051881e60.png">

This lead to issue that the homebridge UI not accessible.
<img width="879" alt="image" src="https://user-images.githubusercontent.com/8107509/166132377-eca7a57d-9fca-4985-a545-55e2cc38fa37.png">

**To Reproduce:**

Synology model: ds218j 
Homebridge app version : 3.00
<img width="700" alt="image" src="https://user-images.githubusercontent.com/8107509/166132405-55464e01-2331-43b9-a5d5-ed3d3e7454cd.png">

**Expected behavior:**

**Logs:**

```
Show the Homebridge / Homebridge Config UI X logs here.
```

**Homebridge Config:**

```json
Show your homebridge config.json here
```

**Screenshots:**

**Environment:**

* **Node.js Version**: 
* **NPM Version**: 
* **Homebridge Version**:  3 
* **Homebridge Config UI X Version**:
* **Operating System**: Synology NAS
* **Process Supervisor**: Docker / Systemd / init.d / pm2 / launchctl / hb-service / other / none

**Comment by oznu** [comment]
Did you stop the app? Or did it fail to launch?

**Comment by oznu** [comment]
If you're happy to help debug this (I can't feasibly test on all Synology NAS model types). Please try the following.

Connect to your nas via ssh. You may need to enable it.

Run this command and provide the output:

```
uname -a
```

Then, with the app "started" in Package Center, try and run this command:

```
sudo hb-shell
```

If that works, and you get put into the "Homebridge Terminal", try and run the following and provide the output of both:

```
node -v
```

```
hb-service -v
```

**Comment by wingmyway** [comment]
After installation, it was running successfully but when I click on the URL it direct me to the page where showing unable to be connected, as below : 

<img width="728" alt="image" src="https://user-images.githubusercontent.com/8107509/166133025-8498fb9f-04a2-452e-81dd-db3cccdc882e.png">

Below is detail info when I ssh to my server. 


`zhigeli@zhigeli:~$ uname -a
Linux zhigeli 3.10.108 #42218 SMP Mon Oct 18 19:14:53 CST 2021 armv7l GNU/Linux synology_armada38x_ds218j
zhigeli@zhigeli:~$ sudo hb-shell
Password: 
Entering Homebridge Shell. To exit type 'exit'.

Homebridge Terminal for Synology DSM
Note: This is a restricted shell, sudo and npm cannot be used here.

homebridge@zhigeli:/volume1/homebridge $ node -v
node: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
homebridge@zhigeli:/volume1/homebridge $ hb-service -v
This command must be executed as root or with sudo.
homebridge@zhigeli:/volume1/homebridge $ 

`

**Comment by oznu** [comment]
Thanks, I'll see what I can do. I'll pull armada38x support for now.

**Comment by oznu** [comment]
@wingmyway - I think I have fixed this, I can't test myself though.

Can you download the .spk for armada38x from:

https://github.com/oznu/homebridge-syno-spk/releases/tag/3.0.1-test

Direct link: https://github.com/oznu/homebridge-syno-spk/releases/download/3.0.1-test/homebridge-armada38x-3.0.1_debug.spk

Add do a manual install?

----

If it still does not load please run:

```
sudo hb-shell
```

Then provide the output of these commands:

```
node -v
```

```
echo $LD_LIBRARY_PATH
```

**Comment by oznu** [comment]
That's great; thanks for confirming.

I'll publish a new build and re-enable it on synology.homebridge.io
