### ISSUE TITLE
Web-GUI not reachable since update to 3.0.2

### ISSUE THREAD

**Issue by lukenukemmp3** [oznu/homebridge-syno-spk#86]
The title says it all.
Homebridge is working absolutely fine, but I can't do anything on the config or similar.

But it must be said: the package itself is very much amazing, thank you so much for creating this!

**Comment by oznu** [comment]
Need more details about what you're running on. 

Try remove the package and re-install to start with.

**Comment by Bpacway** [comment]
Hello, thank you first for your great work!
  I have the same problem. In addition, the homebridge has sent countless inquiries to homematic. uninstalling and reinstalling is not possible. dsm reports the package is not in the correct format. hopefully this info will help.

**Comment by lukenukemmp3** [comment]
Hey there,
thank you for your quick response and excuse my late answer. My Config:
DS220+
DSM 7.0.1-42218

I also can't get a connection via the Homemanager-App, which worked perfectly fine before.
