### ISSUE TITLE
version for evansport processor on DS214play

### ISSUE THREAD

**Issue by Rel0ne** [oznu/homebridge-syno-spk#87]
Hello, can you build the homebridge synology package for evansport processor which is a x86 32 bit processor.

thx

**Comment by romantymoshyk** [comment]
Hey @Rel0ne, I have prepared PR with arch for Evansport, see https://github.com/oznu/homebridge-syno-spk/pull/90 You can fork it and build via Github actions

**Comment by Rel0ne** [comment]
Hi @romantymoshyk thank you very much for the work, I am a newbie here and I do not know how to build the package, can you share some instructions on how to build. I noticed that the last version 3.0.5 does not include support for evansport processor yet.

**Comment by oznu** [comment]
3.0.6 should support evansport. Thanks @romantymoshyk

**Comment by oznu** [comment]
Please confirm if it actually works 😄

**Comment by Rel0ne** [comment]
version 3.0.6 works on ds214play which has the evansport processor. Thank you @oznu & @romantymoshyk for your help! 🙏
