### ISSUE TITLE
«node-gyp rebuild» error when installing plugin

### ISSUE THREAD

**Issue by bjornand1** [oznu/homebridge-syno-spk#9]
Hi, I have homebridge running on a Synology NAS using the oznu installation that allows installing plugins through the browser interface. When trying to install, I do get the error "node-gyp rebuild" and so on (see below). Is there any way to run the "% apt-get install libpcap-dev" and "% sudo npm install -g homebridge-platform-ring-video-doorbell" commands to install the ring plugin when running homebridge this way?

**Comment by oznu** [comment]
Hi @bjornand1,

In the folder you choose to store the homebridge config.json in there should be a `startup.sh` file that was created. This is a shell file that you can add commands that will get executed every time the container starts.

This image uses alpine linux by default so you should add this command to the bottom of the`startup.sh` file:

```
apk add --no-cache libpcap-dev
```

**Comment by bjornand1** [comment]
Thanks for helping! So, I tried this, adding the command and restarting homebridge. When trying to install the plugin, though, I still get the node-gyp rebuild error:

USER: root
DIR: /homebridge
CMD: npm install --unsafe-perm --save homebridge-platform-ring-video-doorbell@latest


> socketwatcher@0.3.0 install /homebridge/node_modules/socketwatcher
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/socketwatcher/build'
  CXX(target) Release/obj.target/socketwatcher/socket_watcher.o
../socket_watcher.cpp: In static member function 'static void SocketWatcher::New(const Nan::FunctionCallbackInfo<v8::Value>&)':
../socket_watcher.cpp:104:49: warning: 'v8::Local<v8::Object> v8::Function::NewInstance() const' is deprecated: Use maybe version [-Wdeprecated-declarations]
     info.GetReturnValue().Set(cons->NewInstance());
                                                 ^
In file included from /root/.node-gyp/8.9.4/include/node/v8.h:26:0,
                 from /root/.node-gyp/8.9.4/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../socket_watcher.hpp:8,
                 from ../socket_watcher.cpp:5:
/root/.node-gyp/8.9.4/include/node/v8.h:3836:52: note: declared here
   V8_DEPRECATED("Use maybe version", Local<Object> NewInstance() const);
                                                    ^
/root/.node-gyp/8.9.4/include/node/v8config.h:318:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/socketwatcher.node
  COPY Release/socketwatcher.node
make: Leaving directory '/homebridge/node_modules/socketwatcher/build'

> pcap2@3.0.4 install /homebridge/node_modules/pcap2
> node-gyp rebuild

make: Entering directory '/homebridge/node_modules/pcap2/build'
  CXX(target) Release/obj.target/pcap_binding/src/pcap_binding.o
../src/pcap_binding.cc:2:23: fatal error: pcap/pcap.h: No such file or directory
 #include <pcap/pcap.h>
                       ^
compilation terminated.
make: *** [pcap_binding.target.mk:96: Release/obj.target/pcap_binding/src/pcap_binding.o] Error 1
make: Leaving directory '/homebridge/node_modules/pcap2/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.102
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /homebridge/node_modules/pcap2
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN homebridge No description
npm WARN homebridge No repository field.
npm WARN homebridge No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pcap2@3.0.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pcap2@3.0.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


   ╭─────────────────────────────────────╮
   │                                     │
   │   Update available 5.6.0 → 5.7.1    │
   │     Run npm i -g npm to update      │
   │                                     │
   ╰─────────────────────────────────────╯


npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-09T08_17_29_128Z-debug.log

Command failed. Please review log for details

So I assume there is still something that has not been properly put in place?

**Comment by oznu** [comment]
Did you restart the entire container after adding that line to the `startup.sh`? Or did you just restart homebridge via the the homebridge ui?

You'll need to restart the entire container by going to DSM > Docker App > Container > Homebridge > Action > Restart.

**Comment by bjornand1** [comment]
Hah, that made the trick, thanks!!!
