### ISSUE TITLE
Date stamp homebridge log

### ISSUE THREAD

**Issue by Reinvented0** [oznu/homebridge-syno-spk#91]
The date stamp in the log of homebridge is [7/15/2022, 10:13:53 AM] instead of [15/7/2022 10:13:53]. If I issue the command "date' in the terminal it gives the correct notation. How do I change the notation in the logs?

**Comment by oznu** [comment]
These are generated by Homebridge via `new Date().toLocaleString()`

```
node
> new Date().toLocaleString()
```

Not much customisation can be done here.
