### ISSUE TITLE
DSM repository sources

### ISSUE THREAD

**Issue by IngmarStein** [oznu/homebridge-syno-spk#93]
The GitHub workflow in this repo uploads a JSON with package metadata to s3://repo.homebridge.io which appears to be an S3 bucket used by the DSM repo https://synology.homebridge.io. Is the source code of the DSM repo available somewhere? I'd like to distribute an SPK myself so that I can auto-update existing installations, but didn't find an easy way to implement a DSM repo.

I tried to figure out how synology.homebridge.io works but I always get an empty package list as a result (`{"packages":[]}`).

**Comment by oznu** [comment]
There is a lambda function to return the correct payload for the requesting unit.

eg. https://synology.homebridge.io/?arch=avoton&major=7

**Comment by oznu** [comment]
> Is there documentation for the query parameters somewhere?

Not that I could find. I just "reversed engineered" the requests Synology was making

**Comment by IngmarStein** [comment]
Thanks again. Closing this thanks to the info you provided.
Please let me know if you decide to open source the Lamba function and potentially other parts which make up the repo API implementation.
