### ISSUE TITLE
Empty package when adding it manually

### ISSUE THREAD

**Issue by GhostDZ9** [oznu/homebridge-syno-spk#95]
Trying to add homebridge as a new package and it seems like the package is empty

Below is what is shown when navigating to https://synology.homebridge.io
`{"packages":[]}`

**Comment by oznu** [comment]
> Below is what is shown when navigating to https://synology.homebridge.io/
{"packages":[]}

That is expected, the endpoint only returns packages valid for requesting NAS, when manually calling the URL as you have done, the NAS model is not included so it returns no available packages.

**Comment by akojima** [comment]
I have a RS422+ (AMD CPU), but the Package Center doesn't find anything for "Homebridge" after updating the Source List, is the model not supported?

$ uname -a
Linux NAS 4.4.180+ #42661 SMP Mon Jun 27 15:08:06 CST 2022 x86_64 GNU/Linux synology_r1000_rs422+

**Comment by oznu** [comment]
I'll check this out soon.

In the mean time you can download the homebridge-braswell-3.0.8.spk file from the releases page and manually install.

**Comment by GhostDZ9** [comment]
@oznu I have the DS1517+  is this system not supported?

**Comment by oznu** [comment]
What did it say when doing a manual install of the spk?

https://github.com/oznu/homebridge-syno-spk/issues/95#issuecomment-1200247503

**Comment by akojima** [comment]
@oznu manual install worked fine for me. Thanks!

**Comment by GhostDZ9** [comment]
This is the spec for my NAS:
`Model: DS1517+
CPU: INTEL ATOM C2538
DSM: DSM 6.2.4-25556 Update 6`

I know it says on the main page that all intel CPUs are supported, but I still do not see the package even after manually adding it. Am I doing something wrong?

**Comment by oznu** [comment]
> DSM: DSM 6.2.4-25556 Update 6

you need DSM 7.

**Comment by oznu** [comment]
@akojima

> I have a RS422+ (AMD CPU), but the Package Center doesn't find anything for "Homebridge" after updating the Source List, is the model not supported?
> 
> $ uname -a Linux NAS 4.4.180+ #42661 SMP Mon Jun 27 15:08:06 CST 2022 x86_64 GNU/Linux synology_r1000_rs422+

r1000 should now work with the repo.
